/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import controle.Conversoes;
import javax.persistence.EntityManager;
import util.GerenciadorConexao;
import java.awt.Image;
import java.awt.Graphics;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import util.DadosUsuario;

/**
 *
 * @author aluno
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal2
     */
    public TelaPrincipal() {
        Conversoes con = new Conversoes();

        TelaLogin telaLogin = new TelaLogin(null, true);

        telaLogin.setVisible(true);
        if (!telaLogin.isLogou()) {
            dispose();
        } else {

            initComponents();
            jLabel1.setText(" Operador(a): " + String.valueOf(DadosUsuario.getFuncionario().getNome()));
            txtData.setText(con.dataToString(new Date()));
            setIconImage(new javax.swing.ImageIcon(getClass().getResource("/img/alfinete.png")).getImage());
            jMenuFinanceiro.setVisible(false);
            EntityManager gerente = GerenciadorConexao.getGerente();

            setExtendedState(MAXIMIZED_BOTH);
        }

        if (DadosUsuario.getFuncionario().getFuncao().equals("Gerente")) {
            adicionarBotaoRelatorio();
            jMenuFinanceiro.setVisible(true);
        }

//         
//         initComponents();
//          jLabel1.setText(String.valueOf(DadosUsuario.getFuncionario()));
//           setIconImage(new javax.swing.ImageIcon(getClass().getResource("/img/alfinete.png")).getImage());
//         EntityManager gerente = GerenciadorConexao.getGerente();
//         
//         setExtendedState(MAXIMIZED_BOTH);
    }

    private javax.swing.JButton btRelatorio;

    public void adicionarBotaoRelatorio() {

        btRelatorio = new javax.swing.JButton();

        btRelatorio.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btRelatorio.setText("Relatorios");
        btRelatorio.setMaximumSize(new java.awt.Dimension(124, 124));
        btRelatorio.setMinimumSize(new java.awt.Dimension(124, 124));
        btRelatorio.setPreferredSize(new java.awt.Dimension(124, 124));
        btRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/relatorio.png")));
        btRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRelatorioActionPerformed(evt);
            }

        });

        btRelatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btRelatorioMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                btRelatorioMouseExited(evt);
            }
        });
        jPanel2.add(btRelatorio);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        jPanel2 = new javax.swing.JPanel();
        btProduto = new javax.swing.JButton();
        btQuartos = new javax.swing.JButton();
        btServico = new javax.swing.JButton();
        btHospede = new javax.swing.JButton();
        btFuncionario = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btManutencaoQuarto = new javax.swing.JButton();
        ImageIcon icon = new ImageIcon(getClass().getResource("/img/wallpaper_Sistema.jpg"));
        Image image = icon.getImage();
        jDesktopPane2 =  new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        //ImageIcon icon = new ImageIcon(getClass().getResource("/img/pexels-ahmed-abdelaziz-453201.jpg"));Image image = icon.getImage();
        ImageIcon icon2 = new ImageIcon(getClass().getResource("/img/pexels-ahmed-abdelaziz-453201.jpg"));
        Image image2 = icon2.getImage();
        jDesktopPane1 =  new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image2,0,0,getWidth(),getHeight(),this);
            }
        };
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btSair = new javax.swing.JButton();
        txtData = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastros = new javax.swing.JMenu();
        jMenuItemProdutos = new javax.swing.JMenuItem();
        jMenuItemHospede = new javax.swing.JMenuItem();
        jMenuHospedagem = new javax.swing.JMenu();
        jMenuItemHospedagem = new javax.swing.JMenuItem();
        jMenuConsultas = new javax.swing.JMenu();
        jMenuItemConsultaProdutos = new javax.swing.JMenuItem();
        jMenuItemConsultaQuartos = new javax.swing.JMenuItem();
        jMenuItemConsultaServicos = new javax.swing.JMenuItem();
        jMenuItemConsultaHospedagem = new javax.swing.JMenuItem();
        jMenuFinanceiro = new javax.swing.JMenu();
        jMenuItemRelatorios = new javax.swing.JMenuItem();
        jMenuConfig = new javax.swing.JMenu();
        jMenuTrocaFundo = new javax.swing.JMenu();
        jMenuItemFundo1 = new javax.swing.JMenuItem();
        jMenuItemFundo2 = new javax.swing.JMenuItem();
        jMenuSessao = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(140, 104, 101));
        jPanel2.setPreferredSize(new java.awt.Dimension(1106, 90));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        btProduto.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/caixa.png"))); // NOI18N
        btProduto.setText("Produtos");
        btProduto.setMaximumSize(new java.awt.Dimension(124, 124));
        btProduto.setMinimumSize(new java.awt.Dimension(124, 124));
        btProduto.setPreferredSize(new java.awt.Dimension(124, 124));
        btProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btProdutoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btProdutoMouseExited(evt);
            }
        });
        btProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProdutoActionPerformed(evt);
            }
        });
        jPanel2.add(btProduto);

        btQuartos.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btQuartos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cama-de-casal.png"))); // NOI18N
        btQuartos.setText("Quartos");
        btQuartos.setMaximumSize(new java.awt.Dimension(124, 124));
        btQuartos.setMinimumSize(new java.awt.Dimension(124, 124));
        btQuartos.setPreferredSize(new java.awt.Dimension(124, 124));
        btQuartos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btQuartosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btQuartosMouseExited(evt);
            }
        });
        btQuartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQuartosActionPerformed(evt);
            }
        });
        jPanel2.add(btQuartos);

        btServico.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ordem-de-servico.png"))); // NOI18N
        btServico.setText("Serviços");
        btServico.setMaximumSize(new java.awt.Dimension(300, 300));
        btServico.setMinimumSize(new java.awt.Dimension(124, 124));
        btServico.setPreferredSize(new java.awt.Dimension(150, 125));
        btServico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btServicoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btServicoMouseExited(evt);
            }
        });
        btServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btServicoActionPerformed(evt);
            }
        });
        jPanel2.add(btServico);

        btHospede.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btHospede.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/avaliacao-do-cliente.png"))); // NOI18N
        btHospede.setText("Hospedes");
        btHospede.setMaximumSize(new java.awt.Dimension(124, 124));
        btHospede.setMinimumSize(new java.awt.Dimension(124, 124));
        btHospede.setPreferredSize(new java.awt.Dimension(124, 124));
        btHospede.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btHospedeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btHospedeMouseExited(evt);
            }
        });
        btHospede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHospedeActionPerformed(evt);
            }
        });
        jPanel2.add(btHospede);

        btFuncionario.setFont(new java.awt.Font("Liberation Sans", 3, 14)); // NOI18N
        btFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/funcionarios.png"))); // NOI18N
        btFuncionario.setText("Funcionários");
        btFuncionario.setMaximumSize(new java.awt.Dimension(124, 124));
        btFuncionario.setMinimumSize(new java.awt.Dimension(124, 124));
        btFuncionario.setPreferredSize(new java.awt.Dimension(124, 124));
        btFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btFuncionarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btFuncionarioMouseExited(evt);
            }
        });
        btFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFuncionarioActionPerformed(evt);
            }
        });
        jPanel2.add(btFuncionario);

        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hospedagem.png"))); // NOI18N
        jButton1.setText("Hospedagens");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        btManutencaoQuarto.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btManutencaoQuarto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/manutencao.png"))); // NOI18N
        btManutencaoQuarto.setText("Manutenção");
        btManutencaoQuarto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btManutencaoQuartoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btManutencaoQuartoMouseExited(evt);
            }
        });
        btManutencaoQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btManutencaoQuartoActionPerformed(evt);
            }
        });
        jPanel2.add(btManutencaoQuarto);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2055, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 817, Short.MAX_VALUE)
        );

        jDesktopPane2.setLayer(jDesktopPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        getContentPane().add(jDesktopPane2, java.awt.BorderLayout.CENTER);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(1060, 45));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_sistema_by_Giovana.png"))); // NOI18N
        jLabel1.setText("(c) Robson, 2022 Tecnico Informatica");

        btSair.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btSair.setForeground(new java.awt.Color(255, 0, 0));
        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sair.png"))); // NOI18N
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        txtData.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        txtData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtData.setText("data");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1265, Short.MAX_VALUE)
                .addComponent(btSair))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(btSair)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(txtData))
                .addContainerGap())
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jMenuCadastros.setText("Cadastros");

        jMenuItemProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItemProdutos.setText("Produto");
        jMenuItemProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProdutosActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemProdutos);

        jMenuItemHospede.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItemHospede.setText("Hospede");
        jMenuItemHospede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHospedeActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemHospede);

        jMenuBar1.add(jMenuCadastros);

        jMenuHospedagem.setText("Hospedagem");

        jMenuItemHospedagem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_SPACE, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItemHospedagem.setText("Criar Hospedagem");
        jMenuItemHospedagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHospedagemActionPerformed(evt);
            }
        });
        jMenuHospedagem.add(jMenuItemHospedagem);

        jMenuBar1.add(jMenuHospedagem);

        jMenuConsultas.setText("Consultas");

        jMenuItemConsultaProdutos.setText("Produtos");
        jMenuItemConsultaProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaProdutosActionPerformed(evt);
            }
        });
        jMenuConsultas.add(jMenuItemConsultaProdutos);

        jMenuItemConsultaQuartos.setText("Quartos");
        jMenuItemConsultaQuartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaQuartosActionPerformed(evt);
            }
        });
        jMenuConsultas.add(jMenuItemConsultaQuartos);

        jMenuItemConsultaServicos.setText("Serviços");
        jMenuItemConsultaServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaServicosActionPerformed(evt);
            }
        });
        jMenuConsultas.add(jMenuItemConsultaServicos);

        jMenuItemConsultaHospedagem.setText("Hospedagem");
        jMenuItemConsultaHospedagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaHospedagemActionPerformed(evt);
            }
        });
        jMenuConsultas.add(jMenuItemConsultaHospedagem);

        jMenuBar1.add(jMenuConsultas);

        jMenuFinanceiro.setText("Financeiro");

        jMenuItemRelatorios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItemRelatorios.setText("Relatorios");
        jMenuFinanceiro.add(jMenuItemRelatorios);

        jMenuBar1.add(jMenuFinanceiro);

        jMenuConfig.setText("Configurações");

        jMenuTrocaFundo.setText("Trocar Plano de Fundo");

        jMenuItemFundo1.setText("Plano 1");
        jMenuItemFundo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItemFundo1MouseClicked(evt);
            }
        });
        jMenuItemFundo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFundo1ActionPerformed(evt);
            }
        });
        jMenuTrocaFundo.add(jMenuItemFundo1);

        jMenuItemFundo2.setText("Plano 2");
        jMenuItemFundo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFundo2ActionPerformed(evt);
            }
        });
        jMenuTrocaFundo.add(jMenuItemFundo2);

        jMenuConfig.add(jMenuTrocaFundo);

        jMenuBar1.add(jMenuConfig);

        jMenuSessao.setText("Sessão");

        jMenuItemSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuSessao.add(jMenuItemSair);

        jMenuBar1.add(jMenuSessao);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 private void btRelatorioActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        TelaRelatorios telaR = new TelaRelatorios(this, true);
        telaR.setVisible(true);
    }
    private void btProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProdutoActionPerformed
        // TODO add your handling code here:
        TelaProduto telaP = new TelaProduto(this, true);
        telaP.setVisible(true);
    }//GEN-LAST:event_btProdutoActionPerformed

    private void btQuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQuartosActionPerformed
        // TODO add your handling code here:
        TelaQuartos telaQ = new TelaQuartos(this, true);
        telaQ.setVisible(true);
    }//GEN-LAST:event_btQuartosActionPerformed

    private void btServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btServicoActionPerformed
        // TODO add your handling code here:
        TelaServico telaS = new TelaServico(this, true);

        telaS.setVisible(true);
    }//GEN-LAST:event_btServicoActionPerformed

    private void btHospedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHospedeActionPerformed
        // TODO add your handling code here:
        TelaHospede telaH = new TelaHospede(this, true);

        telaH.setVisible(true);
    }//GEN-LAST:event_btHospedeActionPerformed

    private void btFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFuncionarioActionPerformed
        // TODO add your handling code here:
        if (DadosUsuario.getFuncionario().getFuncao().equals("Gerente")) {
            TelaFuncionario telaMF = new TelaFuncionario(this, true);

            telaMF.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Acesso Negado!, Você não tem altorização para acessar esse modulo");
        }


    }//GEN-LAST:event_btFuncionarioActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        // TODO add your handling code here:
        dispose();
        TelaPrincipal tela = new TelaPrincipal();
        tela.setVisible(true);
    }//GEN-LAST:event_btSairActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        TelaHospedagem tela = new TelaHospedagem(this, true);

        tela.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btManutencaoQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btManutencaoQuartoActionPerformed
        // TODO add your handling code here:
        TelaAlterarStatusQuarto telaASQ = new TelaAlterarStatusQuarto(null, true);
        telaASQ.setVisible(true);
    }//GEN-LAST:event_btManutencaoQuartoActionPerformed

    private void jMenuItemConsultaQuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaQuartosActionPerformed
        // TODO add your handling code here:
        TelaQuartos tela = new TelaQuartos(null, true);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemConsultaQuartosActionPerformed

    private void jMenuItemProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProdutosActionPerformed
        // TODO add your handling code here:
        TelaManutProduto telaMP = new TelaManutProduto(null, true);
        telaMP.setVisible(true);
    }//GEN-LAST:event_jMenuItemProdutosActionPerformed

    private void jMenuItemHospedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHospedeActionPerformed
        // TODO add your handling code here:
        TelaManutHospede tela = new TelaManutHospede(null, true);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemHospedeActionPerformed

    private void jMenuItemHospedagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHospedagemActionPerformed
        // TODO add your handling code here:
        TelaManutHospedagem tela = new TelaManutHospedagem(null, true);
        tela.disableButoonsConsumo(false);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemHospedagemActionPerformed

    private void jMenuItemConsultaProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaProdutosActionPerformed
        // TODO add your handling code here:
        TelaProduto tela = new TelaProduto(null, true);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemConsultaProdutosActionPerformed

    private void jMenuItemConsultaServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaServicosActionPerformed
        // TODO add your handling code here:
        TelaServico tela = new TelaServico(null, true);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemConsultaServicosActionPerformed

    private void jMenuItemConsultaHospedagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaHospedagemActionPerformed
        // TODO add your handling code here:
        TelaHospedagem tela = new TelaHospedagem(null, true);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemConsultaHospedagemActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        // TODO add your handling code here:
        dispose();
        TelaPrincipal tela = new TelaPrincipal();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemFundo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemFundo1MouseClicked
        // TODO add your handling code here:
        initComponents();
    }//GEN-LAST:event_jMenuItemFundo1MouseClicked


    private void jMenuItemFundo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFundo1ActionPerformed
        // TODO add your handling code here:
        jDesktopPane1.setVisible(true);


    }//GEN-LAST:event_jMenuItemFundo1ActionPerformed

    private void jMenuItemFundo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFundo2ActionPerformed
        jDesktopPane1.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemFundo2ActionPerformed

    private void btProdutoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btProdutoMouseEntered
        // TODO add your handling code here:
        //  btProduto.setBackground(new java.awt.Color(102,255,102));
        btProduto.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 255, 0)));
    }//GEN-LAST:event_btProdutoMouseEntered

    private void btProdutoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btProdutoMouseExited
        // TODO add your handling code here:
        btProduto.setBorder(null);
    }//GEN-LAST:event_btProdutoMouseExited

    private void btQuartosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btQuartosMouseEntered
        // TODO add your handling code here:
        btQuartos.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 255, 0)));
    }//GEN-LAST:event_btQuartosMouseEntered

    private void btQuartosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btQuartosMouseExited
        // TODO add your handling code here:
        btQuartos.setBorder(null);
    }//GEN-LAST:event_btQuartosMouseExited

    private void btServicoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btServicoMouseEntered
        // TODO add your handling code here:
        btServico.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 255, 0)));
    }//GEN-LAST:event_btServicoMouseEntered

    private void btServicoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btServicoMouseExited
        // TODO add your handling code here:
        btServico.setBorder(null);
    }//GEN-LAST:event_btServicoMouseExited

    private void btHospedeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btHospedeMouseEntered
        // TODO add your handling code here:
        btHospede.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 255, 0)));
    }//GEN-LAST:event_btHospedeMouseEntered

    private void btHospedeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btHospedeMouseExited
        // TODO add your handling code here:
        btHospede.setBorder(null);
    }//GEN-LAST:event_btHospedeMouseExited

    private void btFuncionarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btFuncionarioMouseEntered
        // TODO add your handling code here:
        btFuncionario.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 255, 0)));
    }//GEN-LAST:event_btFuncionarioMouseEntered

    private void btFuncionarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btFuncionarioMouseExited
        // TODO add your handling code here:
        btFuncionario.setBorder(null);
    }//GEN-LAST:event_btFuncionarioMouseExited

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 255, 0)));
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
        jButton1.setBorder(null);
    }//GEN-LAST:event_jButton1MouseExited

    private void btManutencaoQuartoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btManutencaoQuartoMouseEntered
        // TODO add your handling code here:
        btManutencaoQuarto.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 255, 0)));
    }//GEN-LAST:event_btManutencaoQuartoMouseEntered

    private void btManutencaoQuartoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btManutencaoQuartoMouseExited
        // TODO add your handling code here:
        btManutencaoQuarto.setBorder(null);
    }//GEN-LAST:event_btManutencaoQuartoMouseExited
    private void btRelatorioMouseEntered(java.awt.event.MouseEvent evt) {
        btRelatorio.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 255, 0)));
    }

    private void btRelatorioMouseExited(java.awt.event.MouseEvent evt) {
        btRelatorio.setBorder(null);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);

            }

        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFuncionario;
    private javax.swing.JButton btHospede;
    private javax.swing.JButton btManutencaoQuarto;
    private javax.swing.JButton btProduto;
    private javax.swing.JButton btQuartos;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btServico;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastros;
    private javax.swing.JMenu jMenuConfig;
    private javax.swing.JMenu jMenuConsultas;
    private javax.swing.JMenu jMenuFinanceiro;
    private javax.swing.JMenu jMenuHospedagem;
    private javax.swing.JMenuItem jMenuItemConsultaHospedagem;
    private javax.swing.JMenuItem jMenuItemConsultaProdutos;
    private javax.swing.JMenuItem jMenuItemConsultaQuartos;
    private javax.swing.JMenuItem jMenuItemConsultaServicos;
    private javax.swing.JMenuItem jMenuItemFundo1;
    private javax.swing.JMenuItem jMenuItemFundo2;
    private javax.swing.JMenuItem jMenuItemHospedagem;
    private javax.swing.JMenuItem jMenuItemHospede;
    private javax.swing.JMenuItem jMenuItemProdutos;
    private javax.swing.JMenuItem jMenuItemRelatorios;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenu jMenuSessao;
    private javax.swing.JMenu jMenuTrocaFundo;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel txtData;
    // End of variables declaration//GEN-END:variables
}
