/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package visao;

import controle.ControleQuarto;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Quarto;
import util.DadosUsuario;

/**
 *
 * @author aluno
 */
public class TelaQuartos extends javax.swing.JDialog {

    ArrayList<Quarto> listaQuartos = new ArrayList<>();
    ControleQuarto contQuarto = new ControleQuarto();

    public TelaQuartos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        jTQuartos.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTQuartos.getColumnModel().getColumn(1).setPreferredWidth(180);
        jTQuartos.getColumnModel().getColumn(2).setPreferredWidth(40);
        jTQuartos.getColumnModel().getColumn(3).setPreferredWidth(20);
        atualizaTabela(true);

        if (!DadosUsuario.getFuncionario().getFuncao().equals("Gerente")) {
            btCadastrar.setEnabled(false);
            btEditar.setEnabled(false);
            btExcluir.setEnabled(false);
            btCadastrarTipo.setEnabled(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void atualizaTabela(boolean flag) {
        // pega o modelo da tabela, que foi definido para 
        // a inclusão dos dados
        DefaultTableModel modelo = (DefaultTableModel) jTQuartos.getModel();

        // enquanto houver linhas na tabela
        if (flag) {
            listaQuartos.clear();
            listaQuartos.addAll(contQuarto.listarTodas());

        }
        while (modelo.getRowCount() > 0) {
            // apaga a primeira linha
            modelo.removeRow(0);
        }
        //modelo.setNumRows(0);

        // percorre o ArrayList de salas
        for (Quarto q : listaQuartos) {
            // adiciona uma linha na tabela
            // o object criado tem que ter a mesma quantidade
            // de elementos que foi definida na tabela, 
            // como também os mesmos tipos

            modelo.addRow(new Object[]{q.getNumero_quarto(), q.getBloco(), q.getTipo().getNome_tipo(), q.isStatus()});
        }

    }

    @SuppressWarnings("unchecked")

    private void limparCampo() {
//    jTNome.setText("");
//        jTDescricao.setText("");
//        jTQuantidade.setText("");
//        jValor.setText("");
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTQuartos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btCadastrar = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btVisualizar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        tfPesquisar = new javax.swing.JTextField();
        jComboFiltro = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btCadastrarTipo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelPrincipal.setBackground(new java.awt.Color(222, 178, 151));

        jTQuartos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Número", "Bloco", "Tipo", "Status"
            }
        ));
        jTQuartos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTQuartosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTQuartos);
        if (jTQuartos.getColumnModel().getColumnCount() > 0) {
            jTQuartos.getColumnModel().getColumn(0).setResizable(false);
            jTQuartos.getColumnModel().getColumn(1).setResizable(false);
            jTQuartos.getColumnModel().getColumn(2).setResizable(false);
            jTQuartos.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel1.setBackground(new java.awt.Color(222, 178, 151));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        btCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/registro.png"))); // NOI18N
        btCadastrar.setText("Cadastrar");
        btCadastrar.setMaximumSize(new java.awt.Dimension(124, 124));
        btCadastrar.setMinimumSize(new java.awt.Dimension(124, 124));
        btCadastrar.setPreferredSize(new java.awt.Dimension(124, 124));
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(btCadastrar);

        btEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar-arquivo.png"))); // NOI18N
        btEditar.setText("Editar");
        btEditar.setMaximumSize(new java.awt.Dimension(124, 124));
        btEditar.setMinimumSize(new java.awt.Dimension(124, 124));
        btEditar.setPreferredSize(new java.awt.Dimension(124, 124));
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btEditar);

        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/excluir.png"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.setMaximumSize(new java.awt.Dimension(124, 124));
        btExcluir.setMinimumSize(new java.awt.Dimension(124, 124));
        btExcluir.setPreferredSize(new java.awt.Dimension(124, 124));
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(btExcluir);

        btVisualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/visualizador-de-dados.png"))); // NOI18N
        btVisualizar.setText("Visualizar");
        btVisualizar.setMaximumSize(new java.awt.Dimension(124, 124));
        btVisualizar.setMinimumSize(new java.awt.Dimension(124, 124));
        btVisualizar.setPreferredSize(new java.awt.Dimension(124, 124));
        btVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVisualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btVisualizar);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sair.png"))); // NOI18N
        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quarto.png"))); // NOI18N
        jLabel1.setText("Tela de Quartos");

        tfPesquisar.setToolTipText("Pesquisa de quartos, podem ser consultados por tipo, número ou status!");
        tfPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfPesquisarKeyReleased(evt);
            }
        });

        jComboFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Por Número", "Por Tipo", "Por Status" }));
        jComboFiltro.setToolTipText("");

        jLabel2.setText("Filtro de Pesquisa:");

        jLabel3.setText("Pesquisar Quartos:");

        btCadastrarTipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-informações-30.png"))); // NOI18N
        btCadastrarTipo.setText("Cadastrar Tipo");
        btCadastrarTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarTipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboFiltro, 0, 127, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap())
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addComponent(btCadastrarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))))
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1)
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addComponent(btCadastrarTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(7, 7, 7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -5, 750, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTQuartosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTQuartosMouseClicked
        // pega a posicao selecionada no listbox
        int posicao = jTQuartos.getSelectedRow();

        // pega o patrimonio  na lista de patrimonios
        Quarto q = listaQuartos.get(posicao);

        // colocar os atributos na tela
//        jTNome.setText(String.valueOf(p.getNome_produto()));
//        jTDescricao.setText(String.valueOf(p.getDescricao()));
//        jTQuantidade.setText(String.valueOf(p.getQtd()));
//        jValor.setText(String.valueOf(p.getValor()));        // TODO add your handling code here:
    }//GEN-LAST:event_jTQuartosMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        // TODO add your handling code here:
        TelaManutQuarto telaMQ = new TelaManutQuarto(null, true);

        telaMQ.setVisible(true);
        atualizaTabela(true);
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        // TODO add your handling code here:

        if (jTQuartos.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Você Não Selecionou Nenhum Quarto");
        } else {
            TelaManutQuarto telaMQ = new TelaManutQuarto(null, true);
            int posicao = jTQuartos.getSelectedRow();
            Quarto q = listaQuartos.get(posicao);
            telaMQ.setQuarto(q);

            telaMQ.setVisible(true);

            atualizaTabela(true);
        }


    }//GEN-LAST:event_btEditarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        int posicao = jTQuartos.getSelectedRow();

        if (jTQuartos.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Você Não Selecionou Nenhum Quarto para excluir!");
        } else {
            Quarto q = listaQuartos.get(posicao);

            int input = JOptionPane.showConfirmDialog(this,
                    "Tem certeza que dejesa excluir este quarto?", "Confirmação de exclusão",
                    JOptionPane.OK_CANCEL_OPTION);

            if (input == 0) {

                try {
                    contQuarto.excluir(q);
                    atualizaTabela(true);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Não é possível excluir este Quarto, pois faz parte de uma hospedagem realizada!");
                }

            }

        }
// TODO add your handling code here:
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVisualizarActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:

        if (jTQuartos.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Você Não Selecionou Nenhum Quarto");
        } else {
            TelaManutQuarto telaMQ = new TelaManutQuarto(null, true);
            int posicao = jTQuartos.getSelectedRow();
            Quarto q = listaQuartos.get(posicao);
            telaMQ.setQuartoView(q);

            telaMQ.setVisible(true);

        }

    }//GEN-LAST:event_btVisualizarActionPerformed

    private void tfPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPesquisarKeyReleased
        // TODO add your handling code here:
        if (tfPesquisar.getText().equals("")) {
            atualizaTabela(true);
        } else {
            listaQuartos.clear();

            switch (jComboFiltro.getSelectedItem().toString()) {
                case "Por Número":
                    listaQuartos.addAll(contQuarto.listarPorNumero(Integer.valueOf(tfPesquisar.getText())));
                    break;
                case "Por Tipo":
                    listaQuartos.addAll(contQuarto.listarPorTipo(tfPesquisar.getText()));
                    break;
                case "Por Status":
                    listaQuartos.addAll(contQuarto.listarPorStatus(tfPesquisar.getText()));
                    break;
            }

            atualizaTabela(false);
        }

    }//GEN-LAST:event_tfPesquisarKeyReleased

    private void btCadastrarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarTipoActionPerformed
        // TODO add your handling code here:
       TelaTipos t = new TelaTipos(null,true);
       t.setVisible(true);
        
    }//GEN-LAST:event_btCadastrarTipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaQuartos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaQuartos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaQuartos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaQuartos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaQuartos dialog = new TelaQuartos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btCadastrarTipo;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btVisualizar;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboFiltro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTQuartos;
    private javax.swing.JTextField tfPesquisar;
    // End of variables declaration//GEN-END:variables
}
