/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package visao;

import controle.ControleHospedagem;
import java.awt.Color;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author aluno
 */
public class TelaRelatorios extends javax.swing.JDialog {

    /**
     * Creates new form TelaRelatorios
     */
    public TelaRelatorios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    ControleHospedagem contHospedagem = new ControleHospedagem();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jDateHospedagem = new com.toedter.calendar.JDateChooser();
        btListarPorData = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btHospedagensEmAtraso = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btHospedagensEmAtraso1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(222, 178, 151));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/relatorio2.png"))); // NOI18N
        jLabel1.setText("Realátorios");

        jLabel2.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        jLabel2.setText("Hospedagens Realizadas em:");

        btListarPorData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-pesquisar-30.png"))); // NOI18N
        btListarPorData.setText("Listar");
        btListarPorData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListarPorDataActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sair.png"))); // NOI18N
        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(222, 178, 151));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        btHospedagensEmAtraso.setBackground(new java.awt.Color(255, 255, 255));
        btHospedagensEmAtraso.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btHospedagensEmAtraso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btHospedagensEmAtrasoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btHospedagensEmAtrasoMouseExited(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Hospedagens em Atraso ");

        javax.swing.GroupLayout btHospedagensEmAtrasoLayout = new javax.swing.GroupLayout(btHospedagensEmAtraso);
        btHospedagensEmAtraso.setLayout(btHospedagensEmAtrasoLayout);
        btHospedagensEmAtrasoLayout.setHorizontalGroup(
            btHospedagensEmAtrasoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btHospedagensEmAtrasoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                .addContainerGap())
        );
        btHospedagensEmAtrasoLayout.setVerticalGroup(
            btHospedagensEmAtrasoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btHospedagensEmAtrasoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(btHospedagensEmAtraso);

        btHospedagensEmAtraso1.setBackground(new java.awt.Color(255, 255, 255));
        btHospedagensEmAtraso1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btHospedagensEmAtraso1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btHospedagensEmAtraso1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btHospedagensEmAtraso1MouseExited(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Hospedagens que encerram hoje ");

        javax.swing.GroupLayout btHospedagensEmAtraso1Layout = new javax.swing.GroupLayout(btHospedagensEmAtraso1);
        btHospedagensEmAtraso1.setLayout(btHospedagensEmAtraso1Layout);
        btHospedagensEmAtraso1Layout.setHorizontalGroup(
            btHospedagensEmAtraso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btHospedagensEmAtraso1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                .addContainerGap())
        );
        btHospedagensEmAtraso1Layout.setVerticalGroup(
            btHospedagensEmAtraso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btHospedagensEmAtraso1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(27, 27, 27))
        );

        jPanel2.add(btHospedagensEmAtraso1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateHospedagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btListarPorData, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btListarPorData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateHospedagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btListarPorDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListarPorDataActionPerformed
        // TODO add your handling code here:

        // Imprimindo o relatÃ³rio a partir de uma lista de usuÃ¡rios listado pelo controle,
        // ou uma lista associada a uma tabela
        // Primeiro passo - alterar os campos do relatÃ³rio no Designer de RelatÃ³rio, utilizando
        // os Fields do Report Inspector, adicionando na propriedade Description
        // o nome do atributo na classe. A propriedade Description Ã© utilizada para 
        // preencher o valor dos Fields com os valores dos objetos existentes na 
        // lista a ser passada para o RelatÃ³rio.
        if (contHospedagem.listarPorData(jDateHospedagem.getDate()).isEmpty()) {
            JOptionPane.showMessageDialog(null, "Não ha Hospedagens Registradas nesta Data!", "Informação", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                System.out.println(contHospedagem.listarPorData(jDateHospedagem.getDate()));
                // cria um objeto da classe JasperReport, ou seja, um relatÃ³rio
                // deve-se passar o caminho onde estÃ¡ o relatÃ³rio dentro do 
                // seu projeto
                JasperReport relatorioCompilado = JasperCompileManager.compileReport("src/relatorios/Relatorio_Hospedagens.jrxml");

                // Preencher o relatÃ³rio com uma lista de usuÃ¡rios passada como um JRBeanCollectionDataSource
                JasperPrint relatorioPreenchido = JasperFillManager.fillReport(relatorioCompilado, null,
                        new JRBeanCollectionDataSource(contHospedagem.listarPorData(jDateHospedagem.getDate())));
                System.out.println(contHospedagem.listarPorData(jDateHospedagem.getDate()));

                // Cria um dialog para colocar o relatório dentro dele
                JDialog tela = new JDialog(this, "Relatório de Hospedagens", true);
                tela.setSize(850, 750);
                tela.setLocationRelativeTo(null);

                // criar um componente swing que contém o relatorio
                JRViewer painelRelatorio = new JRViewer(relatorioPreenchido);

                // adiciona o painel com o relatório dentro do JDialog criado
                tela.getContentPane().add(painelRelatorio);

                // tornar visÃ­vel a janela criada com o relatÃ³rio
                tela.setVisible(true);

            } catch (JRException ex) {
                Logger.getLogger(TelaRelatorios.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Erro ao gerar o relatÃ³rio.");
            }
        }

    }//GEN-LAST:event_btListarPorDataActionPerformed

    private void btHospedagensEmAtrasoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btHospedagensEmAtrasoMouseClicked
        // TODO add your handling code here:

        btHospedagensEmAtraso.setBackground(Color.green);
        if (contHospedagem.listarEmAtraso(new Date()).isEmpty()) {
            JOptionPane.showMessageDialog(null, "Não ha Hospedagens em Atraso!", "Informação", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                System.out.println(contHospedagem.listarEmAtraso(new Date()));
                // cria um objeto da classe JasperReport, ou seja, um relatÃ³rio
                // deve-se passar o caminho onde estÃ¡ o relatÃ³rio dentro do 
                // seu projeto
                JasperReport relatorioCompilado = JasperCompileManager.compileReport("src/relatorios/Relatorio_Hospedagens_Atraso.jrxml");

                // Preencher o relatÃ³rio com uma lista de usuÃ¡rios passada como um JRBeanCollectionDataSource
                JasperPrint relatorioPreenchido = JasperFillManager.fillReport(relatorioCompilado, null,
                        new JRBeanCollectionDataSource(contHospedagem.listarEmAtraso(new Date())));

                // Cria um dialog para colocar o relatório dentro dele
                JDialog tela = new JDialog(this, "Relatório de Hospedagens em Atraso", true);
                tela.setSize(850, 750);
                tela.setLocationRelativeTo(null);

                // criar um componente swing que contém o relatorio
                JRViewer painelRelatorio = new JRViewer(relatorioPreenchido);

                // adiciona o painel com o relatório dentro do JDialog criado
                tela.getContentPane().add(painelRelatorio);

                // tornar visÃ­vel a janela criada com o relatÃ³rio
                tela.setVisible(true);

            } catch (JRException ex) {
                Logger.getLogger(TelaRelatorios.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Erro ao gerar o relatório.");
            }
        }
    }//GEN-LAST:event_btHospedagensEmAtrasoMouseClicked

    private void btHospedagensEmAtraso1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btHospedagensEmAtraso1MouseClicked
        // TODO add your handling code here:
        btHospedagensEmAtraso1.setBackground(Color.green);
        if (contHospedagem.listarEncerraHoje(new Date()).isEmpty()) {
            JOptionPane.showMessageDialog(null, "Não ha Hospedagens para serem encerradas Hoje!", "Informação", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {

                // cria um objeto da classe JasperReport, ou seja, um relatÃ³rio
                // deve-se passar o caminho onde estÃ¡ o relatÃ³rio dentro do 
                // seu projeto
                JasperReport relatorioCompilado = JasperCompileManager.compileReport("src/relatorios/Relatorio_Hospedagens_Fecha_Hoje.jrxml");

                // Preencher o relatÃ³rio com uma lista de usuÃ¡rios passada como um JRBeanCollectionDataSource
                JasperPrint relatorioPreenchido = JasperFillManager.fillReport(relatorioCompilado, null,
                        new JRBeanCollectionDataSource(contHospedagem.listarEncerraHoje(new Date())));

                // Cria um dialog para colocar o relatório dentro dele
                JDialog tela = new JDialog(this, "Relatório de Hospedagens Encerradas Na Data Atual", true);
                tela.setSize(850, 750);
                tela.setLocationRelativeTo(null);

                // criar um componente swing que contém o relatorio
                JRViewer painelRelatorio = new JRViewer(relatorioPreenchido);

                // adiciona o painel com o relatório dentro do JDialog criado
                tela.getContentPane().add(painelRelatorio);

                // tornar visÃ­vel a janela criada com o relatÃ³rio
                tela.setVisible(true);

            } catch (JRException ex) {
                Logger.getLogger(TelaRelatorios.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Erro ao gerar o relatário.");
            }
        }
    }//GEN-LAST:event_btHospedagensEmAtraso1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btHospedagensEmAtrasoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btHospedagensEmAtrasoMouseExited
        // TODO add your handling code here:
        btHospedagensEmAtraso.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_btHospedagensEmAtrasoMouseExited

    private void btHospedagensEmAtraso1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btHospedagensEmAtraso1MouseExited
        // TODO add your handling code here:
        btHospedagensEmAtraso1.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_btHospedagensEmAtraso1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaRelatorios dialog = new TelaRelatorios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btHospedagensEmAtraso;
    private javax.swing.JPanel btHospedagensEmAtraso1;
    private javax.swing.JButton btListarPorData;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateHospedagem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
