/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package visao;

import component.EventItemSelected;
import controle.ControleQuarto;
import java.awt.Color;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import modelo.Quarto;

/**
 *
 * @author aluno
 */
public class teste extends javax.swing.JDialog {

    ControleQuarto contQuartos = new ControleQuarto();
    ArrayList<Quarto> listaQuartos = new ArrayList<>();
    private javax.swing.JButton btQuartosFor;
//    private javax.swing.JPanel jPanel3;
//    private javax.swing.JLabel txtNumero;

    // private javax.swing.JPanel jPanel3;
//    private javax.swing.JPanel jPanel3;
    /**
     * Creates new form teste
     */
    public teste(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        listaQuartos.addAll(contQuartos.listarTodas());

        //jPanel3.setVisible(false);
        initComponents();
         scroll.getViewport().setOpaque(false);
        scroll.setViewportBorder(null);
        scroll.setBorder(null);
        getContentPane().setBackground(new Color(39, 39, 39));
        List<String> items = new ArrayList<>();
        for (Quarto quarto : listaQuartos) {
            items.add("<html> <p><b>Número: </b></p>" + quarto.getNumero_quarto() + "<br /> <p><b>Preço: </b></p>" + quarto.getTipo().getPreco()+ "</html>");
        }
//        for (int i = 1; i <= 20; i++) {
//            items.add("Item " + i);
//        }
        multipleButton.setItems(listaQuartos);
        multipleButton.setEvent(new EventItemSelected() {
            @Override
            public void selected(int index) {
                TelaManutHospedagem tela = new TelaManutHospedagem(null, true);
                tela.setQ(multipleButton.getItems().get(index));
                
                tela.setVisible(true);
                JOptionPane.showMessageDialog(teste.this, multipleButton.getItems().get(index).toString());
            }
        });

    }

    public void adicionarBotao() {

        for (Quarto quarto : listaQuartos) {
            btQuartosFor = new javax.swing.JButton();
            btQuartosFor.setText("<html> <p><b>Número: </b></p>" + quarto.getNumero_quarto() + "<br /> <p><b>Preço: </b></p>" + quarto.getTipo().getPreco()+ "</html>");
            if (quarto.isStatus().equals("Disponivel") || quarto.isStatus().equals("Disponível")) {
                btQuartosFor.setBackground(new java.awt.Color(153, 255, 153));
            } else {
                btQuartosFor.setBackground(new java.awt.Color(255, 51, 51));
            }
            btQuartosFor.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btQuartoForActionPerformed(evt, quarto);
                }
            });

            //btQuartosFor.setText(String.valueOf(quarto.getNumero_quarto()));
//            painelquartos.add(btQuartosFor);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        scroll = new javax.swing.JScrollPane();
        multipleButton = new component.MultipleButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        scroll.setViewportView(multipleButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 879, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btQuartoForActionPerformed(java.awt.event.ActionEvent evt, Quarto q) {
        // TODO add your handling code here:

        System.out.println(q);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                teste dialog = new teste(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private component.MultipleButton multipleButton;
    private javax.swing.JScrollPane scroll;
    // End of variables declaration//GEN-END:variables
}
